# Generated by Django 2.2.1 on 2019-07-13 05:50

from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=100)),
                ('Cid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rname', models.CharField(max_length=200)),
                ('Rid', models.IntegerField(default=0)),
                ('Radd', models.CharField(max_length=300)),
                ('Cid', models.ForeignKey(on_delete=django.db.models.aggregates.Aggregate, to='review.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rvname', models.CharField(max_length=200)),
                ('Rvid', models.IntegerField(default=0)),
                ('Rating', models.IntegerField(default=0)),
                ('Rid', models.ForeignKey(on_delete=django.db.models.aggregates.Aggregate, to='review.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comid', models.IntegerField(default=0)),
                ('Ce_text', models.CharField(max_length=200)),
                ('Rvid', models.ForeignKey(on_delete=django.db.models.aggregates.Aggregate, to='review.Review')),
            ],
        ),
    ]
