# Generated by Django 2.1.7 on 2019-07-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='id',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='Rimage',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Rid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
