# Generated by Django 2.1.7 on 2019-07-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20190720_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Rimage',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
