# Generated by Django 2.1.7 on 2019-07-20 07:51

from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20190720_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Cid',
            field=models.ForeignKey(db_column='Cid', on_delete=django.db.models.aggregates.Aggregate, to='review.Category'),
        ),
    ]
