# Generated by Django 2.2.1 on 2019-07-20 12:36

from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_restaurant_rdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Rvid',
            field=models.ForeignKey(db_column='Rvid', on_delete=django.db.models.aggregates.Aggregate, to='review.Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='Rid',
            field=models.ForeignKey(db_column='Rid', on_delete=django.db.models.aggregates.Aggregate, to='review.Restaurant'),
        ),
    ]
